Repository debtlyteam/debtly, pull requests merged in 2020-05, with the labels that each got.

#22 Added an interface for adding, removing and getting users in the Mong…
  api/database/interface.py
  api/database/templates/users.py
  api/routes/user.py
  api/tests/database/userTest.py
  api/utils/user.py
Labels: backend, mango

#23 Added nice looking login screen
  package-lock.json
  package.json
  public/palette.pdf
  src/components/Login.js
  src/components/Theme.js
  src/icons/debtly.png
  src/views/LoginScreen.js
Labels: frontend

#25 Added an accessor for a user's unique id number
  api/database/interface.py
  api/tests/database/userTest.py
Labels: mango

#28 Merging all templates into one templates.py file. Users can be queried by id or email.
  api/database/interface.py
  api/database/templates.py
  api/database/templates/__init__.py
  api/tests/database/userTest.py
  api/utils/user.py
Labels: backend, mango

#30 Adding flask sessions managed by flask login
  api/database/interface.py
  api/debtly.py
  api/requirements.txt
  api/routes/user.py
  api/utils/password.py
  api/utils/user.py
  src/components/Login.js
Labels: backend
